version: 2
updates:
  # Configuration pour les dépendances npm du frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      - dependency-type: "devDependencies"
        update-types: ["version-update:semver-patch"]

  # Configuration pour les dépendances npm du backend  
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
    ignore:
      - dependency-type: "devDependencies"
        update-types: ["version-update:semver-patch"]

  # Configuration pour les actions GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"

# Configuration de sécurité
security-updates:
  open-pull-requests-limit: 10
