version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: chicha-store-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=chicha_store
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - chicha-network

  redis:
    image: redis:alpine
    container_name: chicha-store-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chicha-network

  backend:
    image: chichastore/backend:${GITHUB_SHA}
    container_name: chicha-store-backend
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/chicha_store
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"
    networks:
      - chicha-network

  frontend:
    image: chichastore/frontend:${GITHUB_SHA}
    container_name: chicha-store-frontend
    restart: always
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chicha-network

  nginx:
    image: nginx:alpine
    container_name: chicha-store-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - chicha-network

volumes:
  mongodb_data:
    driver: local

networks:
  chicha-network:
    driver: bridge
