services:
  - type: web
    name: chicha-store-frontend-service
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: chicha-store-backend-service
    env: node
    region: frankfurt  # Région européenne
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: chicha-store-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: chicha-store-db
    plan: free
    region: frankfurt  # Région européenne
    ipAllowList: []  # Aucune restriction IP
