services:
  - type: web
    name: chicha-store
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node --experimental-specifier-resolution=node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: chicha-store-db
          property: connectionString
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: chicha-store-db
    plan: free
    region: frankfurt  # Région européenne
    ipAllowList: []  # Aucune restriction IP
