name: Security Alerts

on:
  push:
    branches: [ master, dependency-migration-v2 ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * 1' # Tous les lundis à 2h du matin

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm ci
        npm install -g npm-audit-html
    
    - name: Run npm audit
      run: |
        npm audit --audit-level=high > npm-audit-report.html
    
    - name: Upload npm audit report
      uses: actions/upload-artifact@v3
      with:
        name: npm-audit-report
        path: npm-audit-report.html
    
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Rapport d'audit de sécurité disponible
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: failure()
    
    - name: CodeQL Analysis
      uses: github/codeql-action/init@v2
      with:
        languages: javascript
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
    
    - name: Dependabot Compatibility Check
      run: |
        npm outdated || true
        npx npm-check-updates
